### ISSUE TITLE
Add some other licenses

### ISSUE THREAD

**Issue by iNiKe** [mattt/Xcode-Licensed-Templates#11]
Please, add some other often used licenses, just like GPL 2.0, GPL 3.0, LGPL.
Something like https://github.com/Leximosi/Xcode-Licensed-Templates

**Comment by mattt** [comment]
The prevailing wisdom is that [GPL licenses are incompatible with App Store distribution](https://apple.stackexchange.com/questions/6109/is-it-possible-to-have-gpl-software-in-the-mac-app-store). Given that the vast majority of code written in Xcode is destined for the App Store at some point, I don't see a compelling reason to include them here.
